# Generated by Django 3.2.12 on 2022-02-15 14:36

from django.db import migrations, models
import django.utils.timezone
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
        migrations.AddField(
            model_name='produto',
            name='criado',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=stdimage.models.StdImageField(default=django.utils.timezone.now, upload_to='produto', verbose_name='imagem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='modificado',
            field=models.DateField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AddField(
            model_name='produto',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=128, null=True, verbose_name='slug'),
        ),
    ]
