# Generated by Django 3.2.12 on 2022-02-15 14:38

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220215_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=stdimage.models.StdImageField(upload_to='produtos', verbose_name='imagem'),
        ),
    ]
